name: Ubuntu

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgdal-dev libopenscenegraph-dev

    - name: Build
      run: cargo build --release --no-default-features --features "xml"

    
    - name: Test
      run: cargo test --verbose
